=== Viktorious-x/ps5-bdjb-modified-ISOs/Auto_Jailbreak_all_in_one_PS5v20 src/assembly/src/main/resources/bdmv/movieobject.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="movieObjectFile" type="movieObjectFile"/>

  <xs:complexType name="movieObjectFile">
    <xs:sequence>
      <xs:element name="version" type="xs:string"/>
      <xs:element name="movieObjects" type="movieObjects"/>
      <xs:element name="extensionData" type="extensionData"/>
      <xs:element name="paddingsN1" type="xs:int"/>
      <xs:element name="paddingsN2" type="xs:int"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="extensionData">
    <xs:sequence>
      <xs:element name="data" type="xs:short" nillable="true" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="movieObjects">
    <xs:sequence>
      <xs:element name="movieObject" type="movieObject" nillable="true" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="movieObject">
    <xs:sequence>
      <xs:element name="navigationCommands" type="navigationCommand" nillable="true" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element name="terminalInfo" type="terminalInfo" minOccurs="0"/>
    </xs:sequence>
    <xs:attribute name="mobjId" type="xs:int" use="required"/>
  </xs:complexType>

  <xs:complexType name="navigationCommand">
    <xs:sequence>
      <xs:element name="command" type="xs:string" minOccurs="0"/>
    </xs:sequence>
    <xs:attribute name="commandId" type="xs:int" use="required"/>
  </xs:complexType>

  <xs:complexType name="terminalInfo">
    <xs:sequence>
      <xs:element name="menuCallMask" type="xs:boolean"/>
      <xs:element name="resumeIntentionFlag" type="xs:boolean"/>
      <xs:element name="titleSearchMask" type="xs:boolean"/>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== Viktorious-x/ps5-bdjb-modified-ISOs/Auto_Jailbreak_all_in_one_PS5v20 src/assembly/src/main/resources/bdmv/MovieObject.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<movieObjectFile xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                 xsi:noNamespaceSchemaLocation="movieobject.xsd">

  <version>0200</version>
  <movieObjects>
    <movieObject mobjId="0">
      <navigationCommands commandId="0">
        <command>21810000 00000001 00000000</command>
      </navigationCommands>
      <terminalInfo>
        <menuCallMask>false</menuCallMask>
        <resumeIntentionFlag>false</resumeIntentionFlag>
        <titleSearchMask>false</titleSearchMask>
      </terminalInfo>
    </movieObject>
    <movieObject mobjId="1">
      <navigationCommands commandId="0">
        <command>21810000 00000001 00000000</command>
      </navigationCommands>
      <terminalInfo>
        <menuCallMask>false</menuCallMask>
        <resumeIntentionFlag>false</resumeIntentionFlag>
        <titleSearchMask>false</titleSearchMask>
      </terminalInfo>
    </movieObject>
  </movieObjects>
  <extensionData/>
  <paddingsN1>0</paddingsN1>
  <paddingsN2>0</paddingsN2>
</movieObjectFile>
